### ISSUE TITLE
Error for running, list index out of range

### ISSUE THREAD

**Issue by andresvivancov** [myleott/mnist_png#2]
Hello, sorry
Thanks for sharing!!
I was trying to use it but I had an error, could you help me, please?
I downloaded and I tested with the original mnist compressed and uncompressed and also with python 2 and python 3

python convert_mnist_to_png.py /home/andre/mnistX/in3/ /home/andresviv/mnistX/out/

Log:
andresviv@andresviv-ThinkPad-P50:~/mnistX/ULTIMATE/01/mnist_png-master$ python convert_mnist_to_png.py /home/andresviv/mnistX/in3/ /home/andresviv/mnistX/out/
writing /home/andresviv/mnistX/out/training/0/0.png
writing /home/andresviv/mnistX/out/training/3/1.png
Traceback (most recent call last):
  File "convert_mnist_to_png.py", line 68, in <module>
    path.join(output_path, dataset))
  File "convert_mnist_to_png.py", line 47, in write_dataset
    output_filename = path.join(output_dirs[label], str(i) + ".png")
IndexError: list index out of range
andresviv@andresviv-ThinkPad-P50:~/mnistX/ULTIMATE/01/mnist_png-master$ 

![image](https://user-images.githubusercontent.com/15791882/27013406-78730314-4ee3-11e7-8885-aa3b920d4c31.png)

Thank you

**Comment by Allicnam** [comment]
i have the same problem, would like to know how you figured it out!

Edit: i just solved it lol. 

**Solution (Windows 10):**

1) Extract the four .gz mnist packages into your desktop (or whichever directory you're using) 
2) In lines 15,16,18 and 19, change the second dash for a period in the path ( i.e. 'train-images.idx3-ubyte' instead of 'train-images-idx3-ubyte' )

Make sure you send the apropiate path in the arguments and don't change the file names

worked for me at least...

**Comment by Vi5HaL** [comment]
My solution : 
I convert EMNIST balanced by just  increase range of for loop at line :35( in write_dataset() > output_dirs 
for i in range(47))

here Images are rotated 

so to get proper images replace this code at line around 50( i m not sure see code)
`w.write(h, data_i )` with 
` w.write(h, np.rot90(np.fliplr(data_i)))`
 
and add `import numpy as np` at begining

**Comment by ankurjha7** [comment]
Instead of hardcoding value in the range one can also use len(set(labels))) . This will handle all the cases with different labels

**Comment by Vi5HaL** [comment]
Thank you :)
