### ISSUE TITLE
Convert EMNIST dataset to .png

### ISSUE THREAD

**Issue by yash-bhat** [myleott/mnist_png#3]
@myleott 

Hi Myle Ott,

Great work 👍 
I used your script to convert my EMNIST-digits to the required format and voila am happy with the results.
But I cant get around to do the same with letters! (emnist-letters-train-images-idx3-ubyte.gz | emnist-letters-train-labels-idx1-ubyte.gz)

Error: 
```
writing ./train/X/0.png
writing ./train/H/1.png
writing ./train/Q/2.png
writing ./train/P/3.png
writing ./train/X/4.png
writing ./train/R/5.png
writing ./train/N/6.png
writing ./train/L/7.png
writing ./train/W/8.png
writing ./train/Y/9.png
writing ./train/K/10.png
writing ./train/O/11.png
writing ./train/S/12.png
writing ./train/V/13.png
Traceback (most recent call last):
  File "convert_mnist_to_png.py", line 76, in <module>
    path.join(output_path, dataset))
  File "convert_mnist_to_png.py", line 55, in write_dataset
    output_filename = path.join(output_dirs[label], str(i) + ".png")
IndexError: list index out of range
```
I'm new to the field. Any help would be appreciated.
Thanks!

**Comment by Vi5HaL** [comment]
This is because this script is only for 10 classes of digits to get more than 10 we have to increase the range of output_dir
solution :
I convert EMNIST balanced by just increase range of for loop at line :35( in write_dataset() > output_dirs
for i in range(47))

here Images are rotated

To get proper images replace this code at line around 50( i m not sure see code)
`w.write(h, data_i ) `  with
`w.write(h, np.rot90(np.fliplr(data_i)))`

and add import numpy as np at begining

**Comment by nitrlegend** [comment]
how to convert ..i am not able

**Comment by ankurjha7** [comment]
Instead of hardcoding value in the range one can also use len(set(labels))) . This will handle all the cases with different labels
